Part 1 of fixes prior to release...

diff --git a/contrib/deb-builder b/contrib/deb-builder
--- a/contrib/deb-builder
+++ b/contrib/deb-builder
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-DEB_RELEASES="lenny hardy intrepid jaunty karmic lucid"
+DEB_RELEASES="lenny hardy jaunty karmic lucid"
 
 trap "{ echo \"ABORT!!\"; exit 255; }" SIGINT SIGTERM
 if [ $# -eq 1 ]; then
@@ -10,6 +10,11 @@ pdebuild --buildresult ../MTX_Builds/Output/"$dist" --pbuilderroot "sudo DIST=$d
 else
 	echo "Building for dists \"$DEB_RELEASES\""
 	for dist in `echo "$DEB_RELEASES"` ; do
+		echo "Building for Distro $dist"
 		pdebuild --buildresult ../MTX_Builds/Output/"$dist" --pbuilderroot "sudo DIST=$dist"
+		if [ $? -ne 0 ] ; then
+			echo "Build failure for dist $dist"
+			exit -1
+		fi
 	done
 fi
