Revised Makefiles to regen POTFILES.in/SPECIALS.in as needed in order to automatically pickup new files and update the translation tables

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -21,3 +21,28 @@ DISTCLEANFILES = intltool-extract intltool-merge intltool-update po/.intltool-me
 
 EXTRA_DIST = config.rpath m4/ChangeLog configure CREDITS AUTHORS TODO README INSTALL LICENSE ${INTLTOOL_FILES}
 
+
+check-gettext:
+	@if test x$(USE_NLS) != "xyes" ; then echo "Missing gettext. Rerun configure and check for" \
+	"'checking whether to use NLS... yes'!" ; exit 1 ; fi
+
+update-po: check-gettext
+	@find $(srcdir)/ -name "*.c" -print | sort > $(srcdir)/po/POTFILES.in.2 ; 
+	@find $(srcdir)/ -name "*.glade" -print | sort >> $(srcdir)/po/POTFILES.in.2 ; \
+	if diff $(srcdir)/po/POTFILES.in $(srcdir)/po/POTFILES.in.2 >/dev/null 2>&1 ; then \
+		rm -f $(srcdir)/po/POTFILES.in.2 ; \
+	else \
+		mv $(srcdir)/po/POTFILES.in.2 $(srcdir)/po/POTFILES.in ; \
+	fi 
+	@find $(srcdir)/Gui -name "*.in" -print | sort > $(srcdir)/po/SPECIALS.in.2 ; 
+	@find $(srcdir)/RealtimeMaps -name "*map.in" -print | sort >> $(srcdir)/po/SPECIALS.in.2 ; 
+	@find $(srcdir)/RuntimeStatus -name "*conf.in" -print | sort >> $(srcdir)/po/SPECIALS.in.2 ; 
+	@find $(srcdir)/Interrogator -name "*prof.in" -print | sort >> $(srcdir)/po/SPECIALS.in.2 ; \
+	if diff $(srcdir)/po/SPECIALS.in $(srcdir)/po/SPECIALS.in.2 >/dev/null 2>&1 ; then \
+		rm -f $(srcdir)/po/SPECIALS.in.2 ; \
+	else \
+		mv $(srcdir)/po/SPECIALS.in.2 $(srcdir)/po/SPECIALS.in ; \
+	fi 
+	cd po && $(MAKE) $(AM_MAKEFLAGS) update-po
+
+.PHONY: check-gettext update-po
